### PR TITLE
fix: use inferred supported features to set extendedSupportedFeatures

### LINKED ISSUE #4112: v.1.4.0: inferred supported features reported as unsupported in conformance results
**What happened**:
The inferred extended supported features from the `GatewayClass `are still being reported as `unsupportedFeatures` in the conformance report, even though the tests for them passed successfully.

**What you expected to happen**:
The features defined on the GatewayClass as supportedFeatures, for example:
```
   supportedFeatures:
    - name: Gateway
    - name: GatewayInfrastructurePropagation
    - name: GatewayPort8080
    - name: HTTPRoute
    - name: HTTPRouteBackendProtocolH2C
    - name: HTTPRouteBackendProtocolWebSocket
    - name: HTTPRouteBackendTimeout
    - name: HTTPRouteCORS
    - name: HTTPRouteDestinationPortMatching
    - name: HTTPRouteHostRewrite
    - name: HTTPRouteMethodMatching
    - name: HTTPRouteNamedRouteRule
    - name: HTTPRouteParentRefPort
    - name: HTTPRoutePathRedirect
    - name: HTTPRoutePathRewrite
    - name: HTTPRoutePortRedirect
    - name: HTTPRouteQueryParamMatching
    - name: HTTPRouteRequestTimeout
    - name: HTTPRouteResponseHeaderModification
    - name: HTTPRouteSchemeRedirect
    - name: ReferenceGrant
```
Which means should appear under the list of supported features in the conformance report. However, despite all related tests passing, they are incorrectly reported as unsupported:
```
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 20
      Skipped: 0
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayHTTPListenerIsolation
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - GatewayStaticAddresses
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteBackendTimeout
    - HTTPRouteCORS
    - HTTPRouteDestinationPortMatching
    - HTTPRouteHostRewrite
    - HTTPRouteMethodMatching
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
```

**How to reproduce it (as minimally and precisely as possible)**:
Run the conformance tests without explicitly setting any supported features.

**Anything else we need to know?**:
N/A

### PR DESCRIPTION
**Pull request by snorwin**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4112 

**Does this PR introduce a user-facing change?**:

```release-note
Set extended supported/unsupported features in conformance test reports based on inferred supported features
```

### CODE REVIEW

File: conformance/utils/suite/suite.go [hunk 1]
```diff
@@ -309,12 +309,12 @@ func NewConformanceTestSuite(options ConformanceOptions) (*ConformanceTestSuite,
...
 		// that profile which are supported at a Core level of support.
 		for _, f := range conformanceProfile.CoreFeatures.UnsortedList() {
-			if !options.SupportedFeatures.Has(f) {
+			if !suite.SupportedFeatures.Has(f) {
 				suite.SupportedFeatures.Insert(f)
 			}
 		}
 		for _, f := range conformanceProfile.ExtendedFeatures.UnsortedList() {
-			if options.SupportedFeatures.Has(f) {
+			if suite.SupportedFeatures.Has(f) {
```
Comment (LiorLieberman) [inline conformance/utils/suite/suite.go]: I think thats good, but need someone else's eyes on this to confirm.

**Review by LiorLieberman — COMMENTED** [review]
/cc @bexxmodd

File: conformance/utils/suite/suite.go (hunk 1 above)
Comment (bexxmodd) [reply conformance/utils/suite/suite.go]: Can you describe and what's the changing here?

suite.SupportedFeatures is created from options.SupportedFeatures and when we are updating suite.SupoortedFeatures (which will be used for testing) we are checking if the proper features were populated in the options.SupportedFeatures, we don't want simultaneously check and update the same set, as it makes logic vulnerable to some obscure bugs.

P.S. also can you please add unit tests for the fixed logic.

**Comment by LiorLieberman** [comment]
@snorwin IIUC this only messes up reporting, right?

I think this is LGTM from my side, will leave approval for someone else 

/lgtm
/unhold

File: conformance/utils/suite/suite.go (hunk 1 above)
Comment (snorwin) [reply conformance/utils/suite/suite.go]: @bexxmodd the bug is described in #4112.

The issue occurs when supported features are inferred from the GatewayClass, in those cases, they aren’t included in `options.SupportedFeatures` but only set in `suite.SupportedFeatures`. As a result, the conformance test report incorrectly marks them as unsupported.

Comment (bexxmodd) [reply conformance/utils/suite/suite.go]: Discussed this with @LiorLieberman offline. I see the issue.

Just a nit: Can you please use `supportedFeatures` for check, instead of `suite.SupportedFeatures` ? As in above comment, it's not a great practice to update the set that is also checked upon in the loop.

Comment (snorwin) [reply conformance/utils/suite/suite.go]: But then we’d also have to change:
```go
			if !suite.SupportedFeatures.Has(f) {
				suite.SupportedFeatures.Insert(f)
			}
```
to:
```go
			if !supportedFeatures.Has(f) {
				suite.SupportedFeatures.Insert(f)
			}
```
That doesn’t seem right to me. I see `supportedFeatures` as a temporary variable that should only be used until the suite is initialized.

Comment (snorwin) [reply conformance/utils/suite/suite.go]: For unit test coverage, I’d propose adding assertions for `extendedSupportedFeatures` in TestInferGWCSupportedFeatures.

Comment (bexxmodd) [reply conformance/utils/suite/suite.go]: My bad. I meant to use supportedFeatures to check if it has a name or not.

Comment (snorwin) [reply conformance/utils/suite/suite.go]: @bexxmodd I’m not sure I understand what you’re requesting, could you provide a code suggestion?

File: conformance/utils/suite/suite.go [hunk 2]
```diff
@@ -309,12 +309,12 @@ func NewConformanceTestSuite(options ConformanceOptions) (*ConformanceTestSuite,
 		// the use of a conformance profile implicitly enables any features of
 		// that profile which are supported at a Core level of support.
 		for _, f := range conformanceProfile.CoreFeatures.UnsortedList() {
-			if !options.SupportedFeatures.Has(f) {
+			if !suite.SupportedFeatures.Has(f) {
 				suite.SupportedFeatures.Insert(f)
 			}
 		}
 		for _, f := range conformanceProfile.ExtendedFeatures.UnsortedList() {
-			if options.SupportedFeatures.Has(f) {
```
Comment (bexxmodd) [inline conformance/utils/suite/suite.go:317]:
```
if !supportedFeatures.Has(f) {
    suite.SupportedFeatures.Insert(f)
}
```

It's a temporary variable until final supported features are determined for testing and NewConformanceTestSuite returns ConformanceTestSuite. Nothing limits it's scope until suite is initialized. There's no scope conflict or a misleading name so I don't see why it should go out of usage after suite is initialized. it's the sound representation of populated features from the Status field.

Comment (snorwin) [reply conformance/utils/suite/suite.go:317]: In my opinion, it doesn’t make sense to use `supportedFeatures` after it has already been assigned to `suite.SupportedFeatures`. Modifying it at that point would even be incorrect, why should we still rely on it?

In case additional code was inserted above this section that changed `suite.SupportedFeatures`, then the logic here is supposed to use the actual (possibly modified) features of the suite (`suite.SupportedFeatures`) rather than the originally derived ones in `supportedFeatures`.

If it is important that `supportedFeatures` is used in this part, I would suggest moving the entire section before the initialization of the `ConformanceTestSuite` object.

Comment (bexxmodd) [reply conformance/utils/suite/suite.go:317]: It is actually a really good idea to move the whole section before initializing the ConformanceTestSuite.

Comment (snorwin) [reply conformance/utils/suite/suite.go:317]: @bexxmodd could you take a close look at the refactoring? I simplified the logic quite a bit.

Comment (bexxmodd) [reply conformance/utils/suite/suite.go:317]: This is way cleaner! Thanks Norwin!

**Comment by LiorLieberman** [comment]
sweet, thank you! 

/approve
/lgtm
/hold please update release notes and communicate on Slack that this WILL impact reporting from now on.
