### PR TITLE
Fix cors cel

### LINKED ISSUE #3648: CORS documentation and validation are not consistent
The docs say you can have `*.com` and `*`, and the example on https://gateway-api.sigs.k8s.io/geps/gep-1767/?h=cors shows the same. The validation only allows a fully qualified name.

I think the fix is to loosen the validation

### PR DESCRIPTION
**Pull request by rikatz**
**What type of PR is this?**
/kind bug
/kind test

**What this PR does / why we need it**: 
- Adds support for a single "*" as a CORS origin
- Adds validation tests for the AllowOrigins and AllowMethods fields

**Which issue(s) this PR fixes**:
Fixes #3648 

**Does this PR introduce a user-facing change?**:
```release-note
Adds support for a single '*' character on CORS origins
```

### CODE REVIEW

File: apis/v1/shared_types.go [hunk 1]
```diff
@@ -608,6 +608,17 @@ type PreciseHostname string
...
 
+// The CORSOrigin MUST NOT be a relative URI, and it MUST follow the URI syntax and
+// encoding rules specified in RFC3986.  The CORSOrigin MUST include both a
+// scheme (e.g., "http" or "spiffe") and a scheme-specific-part, or it should be a single '*' character.
+// URIs that include an authority MUST include a fully qualified domain name or
+// IP address as the host.
+// <gateway:util:excludeFromCRD> The below regex was generated to simplify the assertion of scheme://host:<port> being port optional </gateway:util:excludeFromCRD>
+// +kubebuilder:validation:MinLength=1
+// +kubebuilder:validation:MaxLength=253
+// +kubebuilder:validation:Pattern=`^\*$|([a-zA-Z][a-zA-Z0-9+\-.]+):\/\/([^:/?#]+)(:([0-9]{1,5}))?$`
```
Comment (snorwin) [inline apis/v1/shared_types.go]:
```suggestion
// +kubebuilder:validation:Pattern=`(^\*$)|(^([a-zA-Z][a-zA-Z0-9+\-.]+):\/\/([^:/?#]+)(:([0-9]{1,5}))?$)`
```
I think it needs a `^` (start of line) in the second alternative.

**Review by snorwin — CHANGES_REQUESTED** [review]

File: apis/v1/shared_types.go (hunk 1 above)
Comment (rikatz) [reply apis/v1/shared_types.go]: ra, good catch! let me fix it here and fix the test

File: pkg/test/cel/httproute_experimental_test.go [hunk 2]
```diff
@@ -241,6 +241,135 @@ func toDuration(durationString string) *gatewayv1.Duration {
...
+					"https://xpto.com:notaport",
+				},
+			},
+		},
+		{
+			name:       "An origin with an value before the scheme definition should be denied",
+			wantErrors: []string{"Invalid value: \"xpto/https://xpto.com\""},
+			corsfilter: &gatewayv1.HTTPCORSFilter{
+				AllowOrigins: []gatewayv1.CORSOrigin{
+					"xpto/https://xpto.com",
```
Comment (rikatz) [inline pkg/test/cel/httproute_experimental_test.go:313]: @snorwin  this is the test for the comment you did. I have also fixed the cel regex :)
