### PR TITLE
fix(gwctl): prevent panic when describing gatewayclasses with no description

### LINKED ISSUE #2849: Description of GatewayClass is nil gives error in gwctl describe
**What happened**:
I deployed `Kong Ingress Controller` on a Kind cluster. When I run `gwctl describe gatewayclasses` I get the following error
```shell
$ go run cmd/main.go describe gatewayclasses
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13ade0e]

goroutine 1 [running]:
sigs.k8s.io/gateway-api/gwctl/pkg/printer.(*GatewayClassesPrinter).PrintDescribeView(0xc000d07980, 0xc000f0c030)
	/home/devaanshk840/Code/gateway-api/gwctl/pkg/printer/gatewayclasses.go:53 +0x10e
sigs.k8s.io/gateway-api/gwctl/pkg/cmd/describe.runDescribe({0xc00100e0d0?, 0x0?, 0x0?}, 0x0?, 0x0?)
	/home/devaanshk840/Code/gateway-api/gwctl/pkg/cmd/describe/describe.go:121 +0x8bc
sigs.k8s.io/gateway-api/gwctl/pkg/cmd/describe.NewDescribeCommand.func1(0xc000c8eb00?, {0xc00100e0d0?, 0x1?, 0x16781b1?})
	/home/devaanshk840/Code/gateway-api/gwctl/pkg/cmd/describe/describe.go:46 +0x2c
github.com/spf13/cobra.(*Command).execute(0xc0001b1500, {0xc00100e0a0, 0x1, 0x1})
	/home/devaanshk840/Code/gateway-api/gwctl/vendor/github.com/spf13/cobra/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b0300)
	/home/devaanshk840/Code/gateway-api/gwctl/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/devaanshk840/Code/gateway-api/gwctl/vendor/github.com/spf13/cobra/command.go:1039
main.main()
	/home/devaanshk840/Code/gateway-api/gwctl/cmd/main.go:68 +0x2a5
exit status 2
```

**Anything else we need to know?**:
This error is occuring at the following line of code https://github.com/kubernetes-sigs/gateway-api/blob/main/gwctl/pkg/printer/gatewayclasses.go#L53 because `gatewayClassNode.GatewayClass.Spec.Description` is a pointer to string and `Kong` does not set a description for its gateway class. So essentially `*gatewayClassNode.GatewayClass.Spec.Description` is trying to dereference a nil pointer.

/area gwctl
/kind bug

### PR DESCRIPTION
**Pull request by pmalek**
**What type of PR is this?**

/kind bug
/area gwctl

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2849 

**Does this PR introduce a user-facing change?**:

```release-note
fix(gwctl): prevent panic when describing gatewayclasses with no description
```

### CODE REVIEW

File: gwctl/pkg/printer/gatewayclasses.go [hunk 1]
```diff
@@ -95,11 +94,19 @@ func (gcp *GatewayClassesPrinter) PrintDescribeView(resourceModel *resourcedisco
 			{
 				Name: gatewayClassNode.GatewayClass.GetName(),
 			},
-			{
+		}
+
+		if gatewayClassNode.GatewayClass.Spec.Description != nil {
+			views = append(views, gatewayClassDescribeView{
 				ControllerName: string(gatewayClassNode.GatewayClass.Spec.ControllerName),
 				Description:    *gatewayClassNode.GatewayClass.Spec.Description,
```
Comment (gauravkghildiyal) [inline gwctl/pkg/printer/gatewayclasses.go:102]: nit: Is it more neat if we simply convert Description to a `*string` and just directly assign:

```
Description: gatewayClassNode.GatewayClass.Spec.Description
```

Alternatively, if we really don't want a pointer, maybe the following is still slightly neater (since it keeps `ControllerName` out of the conditional)?

```
		views := []gatewayClassDescribeView{
			{
				Name: gatewayClassNode.GatewayClass.GetName(),
			},
			{
				ControllerName: string(gatewayClassNode.GatewayClass.Spec.ControllerName),
			},
		}

		if desc := gatewayClassNode.GatewayClass.Spec.Description; desc != nil {
			views = append(views, gatewayClassDescribeView{Description: *desc})
		}
```

**Review by gauravkghildiyal — COMMENTED** [review]
Thanks for the fix @pmalek. Just one minor thought :) (Open for discussion)

File: gwctl/pkg/printer/gatewayclasses.go (hunk 1 above)
Comment (pmalek) [reply gwctl/pkg/printer/gatewayclasses.go]: I didn't want to change the type but sure, why not.  https://github.com/kubernetes-sigs/gateway-api/pull/2894/commits/9cd09fb188032d506368447b23f36f80b7726592

**Comment by gauravkghildiyal** [comment]
Thank you for accommodating!

**Comment by gauravkghildiyal** [comment]
Thank you!

/lgtm
