### PR TITLE
Fix AttachedRoutes documentation aligned to count only Accepted Routes

### LINKED ISSUE #4321: Fix apidoc for attachedRoutes and add conformance test
**What happened**:

During the implementation of ListenerSet and attachedListener field (https://github.com/kubernetes-sigs/gateway-api/pull/4286) we have identified that the description of gateway.status.listenerStatus.attachedRoutes  we have identified that the description does not reflect the reality.

Our description says:
 
```
//the AttachedRoutes field count MUST be set
// for Listeners with condition Accepted: false and MUST count successfully
// attached Routes that may themselves have Accepted: false conditions.
```

but the fact is that at least for Istio, kgateway, envoy gateway and Cilium this count represents `Accepted = true`

This does make sense, as we need to know what are just the valid routes. And ListenerSet is already reflecting this new behavior.

**What you expected to happen**:

* Fix the API description to count only Accepted routes
* Create a conformance test to validate this behavior

### PR DESCRIPTION
**Pull request by davidesalerno**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR is fixing the documentation for the AttachedRoutes field specifying that counts only Accepted = true Routes

**Which issue(s) this PR fixes**:

Fixes #4321 

**Does this PR introduce a user-facing change?**:
```release-note
Fix the description of what conditions count as a valid attachedRoute on Gateway status
```

### CODE REVIEW

**Comment by rikatz** [comment]
/cc @davidjumani @youngnick 

one missing piece on the docs we have recently changed

/ok-to-test

File: apis/v1/gateway_types.go [hunk 1]
```diff
@@ -1398,8 +1398,10 @@ type ListenerStatus struct {
 	// attachment semantics can be found in the documentation on the various
 	// Route kinds ParentRefs fields). Listener or Route status does not impact
 	// successful attachment, i.e. the AttachedRoutes field count MUST be set
-	// for Listeners with condition Accepted: false and MUST count successfully
-	// attached Routes that may themselves have Accepted: false conditions.
+	// for Listeners with condition Accepted: false but MUST count successfully
+	// only attached Routes that may themselves have Accepted: true conditions.
+	// Attached Routes whose Accepted condition is False or Unknown (or that
+	// do not have an Accepted condition set) MUST NOT be included in this count.
```
Comment (robscott) [inline apis/v1/gateway_types.go]: I haven't been following this as closely as I should, but maybe I can reword this to make sure I'm understanding it correctly:

1) `AttachedRoutes` should always be set on each Listener, even if the Listener itself has not been accepted
2) `AttachedRoutes` should only represent the number of Routes with the `Accepted` condition set to `True` that have been attached to this Listener

If so, I'm completely on board with point 2, but confused by point 1 (although I recognize that it's not new in this PR).

/cc @rikatz @youngnick

Comment (davidesalerno) [reply apis/v1/gateway_types.go]: @robscott  Exactly, I changed only point 2 since it is what the issue is requesting, instead for point 1 I can confirm that based on the doc it seems to work in this way.

Comment (rikatz) [reply apis/v1/gateway_types.go]: hey Rob, so long story short, during the update of ListenerSet GEP (https://github.com/kubernetes-sigs/gateway-api/pull/4286/files) Nick questioned why we were counting Listeners not accepted as well, and well, me and @davidjumani copied the text from here.

In fact, the implementations today count just the accepted ones, but the text on the API description was wrong, so we are now "fixing it" and making it clear that AttachedRoutes MUST count just accepted routes.

Maybe @youngnick has some better wording here tho :)

Comment (rikatz) [reply apis/v1/gateway_types.go]: @davidesalerno asked me to clarify here, my point is exactly his: we are touching here just what an attachedRoute means (eg.: instead of any attached route, just accepted attached routes) to reflect the same behavior of attachedListenerSets. 

We are not touching the line that says "if a Listener on a Gateway has accepted=False it still MUST be added", this behavior should remain the same.

Comment (youngnick) [reply apis/v1/gateway_types.go]: I think this is fine, since we will have the conformance tests to validate the correct behavior.

Comment (robscott) [reply apis/v1/gateway_types.go]: This is a tricky one to word in a way that will be easy to understand, but maybe this would be slightly clearer:

```suggestion
	// for Listeners, even if the Accepted condition of an individual Listener is set 
	// to "False". The AttachedRoutes number represents the number of Routes with 
	// the Accepted condition set to "True" that have been attached to this Listener. 
	// Routes with any other value for  the Accepted condition MUST NOT be included
	// in this count.
```

**Review by robscott — COMMENTED** [review]
Thanks @davidesalerno!

File: apis/v1/gateway_types.go (hunk 1 above)
Comment (davidesalerno) [reply apis/v1/gateway_types.go]: @robscott  Thank you for the help in rewording this part, clarifying the fact that for Listener it is not important the Accepted condition it will help for sure!
Suggestion applied ;-)

File: apis/v1/gateway_types.go [hunk 2]
```diff
@@ -1398,8 +1398,11 @@ type ListenerStatus struct {
 	// attachment semantics can be found in the documentation on the various
 	// Route kinds ParentRefs fields). Listener or Route status does not impact
 	// successful attachment, i.e. the AttachedRoutes field count MUST be set
-	// for Listeners with condition Accepted: false and MUST count successfully
-	// attached Routes that may themselves have Accepted: false conditions.
+	// for Listeners, even if the Accepted condition of an individual Listener is set
+	// to "False". The AttachedRoutes number represents the number of Routes with
+	// the Accepted condition set to "True" that have been attached to this Listener.
+	// Routes with any other value for  the Accepted condition MUST NOT be included
```
Comment (robscott) [inline apis/v1/gateway_types.go]: Sorry since this probably came directly from my suggestion, but looks like there was an extra space in here:
```suggestion
	// Routes with any other value for the Accepted condition MUST NOT be included
```

Comment (davidesalerno) [reply apis/v1/gateway_types.go]: @robscott  Blank space removed

**Comment by rikatz** [comment]
/lgtm
thanks @davidesalerno 
/hold cancel
