### PR TITLE
Fix OpenAPI validations by adding API list markers

### LINKED ISSUE #2942: Ensure OpenAPI schema is accurate in the Gateway types
Without the correct annotations Server Side Apply won't work properly.

For example in upstream K8s the PodSpec OpenAPI schema didn't have the correct `x-kubernetes-list-map-keys` & `x-kubernetes-list-type` so you couldn't separate ownership of different containers.

The purpose of the issue is to audit the schema of our types and ensure accuracy

_Originally posted by @dprotaso in https://github.com/kubernetes-sigs/gateway-api/issues/2537#issuecomment-2037740149_

### PR DESCRIPTION
**Pull request by erikgb**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Our openapi generator also generates a report of violations of the Kubernetes API best practices. This report is "thrown away" now, but this PR suggests adding it to Git to raise awareness of the importance of API array metadata. ~I have also tried to fix all reported violations in our APIs, but please review carefully!~ UPDATE: For now, all new list type markers are set to `atomic` (default without the marker), and I have created a WIP PR (https://github.com/kubernetes-sigs/gateway-api/pull/3972) for the proposed bugfixes that we can consider after merging this.

I have also reorganized the markers on some of the affected fields, as I think it's clearer to have a consistent order of the markers.

**Which issue(s) this PR fixes**:

Fixes #2942

**Does this PR introduce a user-facing change?**:

```release-note
Add missing OpenAPI schema metadata to array fields in APIs
```

### CODE REVIEW

**Comment by rikatz** [comment]
hey @erikgb 

As we are moving with the enablement of automated API validations, can you please check https://github.com/kubernetes-sigs/gateway-api/pull/3917 and https://docs.google.com/document/d/1DSyP7Vt9E9wX2ku1C0AvCLqQe9cCiDPCLiPP0wXFYQw/edit?disco=AAABnQWiOX8

and maybe add https://github.com/kubernetes-sigs/kube-api-linter/blob/main/pkg/analysis/ssatags/ to the analyzers list to validate the behavior during CI/CD?

Regarding this being a breaking change or not, per Joel's comment on the document we need to check with API Machinery if this change can represent any harm for already implemented or in use Gateway API resources.

Thanks!

**Comment by erikgb** [comment]
> As we are moving with the enablement of automated API validations, can you please check #3917 and https://docs.google.com/document/d/1DSyP7Vt9E9wX2ku1C0AvCLqQe9cCiDPCLiPP0wXFYQw/edit?disco=AAABnQWiOX8

> and maybe add https://github.com/kubernetes-sigs/kube-api-linter/blob/main/pkg/analysis/ssatags/ to the analyzers list to validate the behavior during CI/CD?

Cool! I didn't know that you were in the process of adding KAL to Gateway API. I will definitely take a look and see if we can validate more in CI/CD.

> Regarding this being a breaking change or not, per Joel's comment on the document we need to check with API Machinery if this change can represent any harm for already implemented or in use Gateway API resources.

Understood! I am a bit curious myself, as we are in the process of adding missing API list markers to cert-manager APIs. So, in general, it would be good to know which changes can be made non-breaking. Of course, the safest would be to mark all lists as `atomic`, which is the current default behavior, but that would be too defensive IMO. WDYT @rikatz?

**Comment by erikgb** [comment]
@rikatz, I have now enabled the `ssatags` analyzer in the KAL configuration, and it reports no issues. I have also reached out to sig-api-machinery on [Slack](https://kubernetes.slack.com/archives/C0EG7JC6T/p1753980723308699) and am waiting for someone to hopefully respond.

**Comment by rikatz** [comment]
> @rikatz, I have now enabled the `ssatags` analyzer in the KAL configuration, and it reports no issues. I have also reached out to sig-api-machinery on [Slack](https://kubernetes.slack.com/archives/C0EG7JC6T/p1753980723308699) and am waiting for someone to hopefully respond.

thank you!

About your questions on what is safer or not, I need to defer to people who actually know what they are doing (which is not me!) 

@youngnick @robscott do you see any issue here? On a previous review on the linter proposal document, @JoelSpeed suggested that we keep the `atomic` for now to keep backward compatibility. I don't really know the impact here for controllers on changing things from `atomic` (the default) to something else.

@erikgb once you have some answer from apimachinery as well, let's see how this fits on the proposal.

Thank you!

File: apis/v1/grpcroute_types.go [hunk 1]
```diff
@@ -137,12 +137,14 @@ type GRPCRouteSpec struct {
 	// Support: Core
 	//
 	// +optional
+	// +listType=set
```
Comment (JoelSpeed) [inline apis/v1/grpcroute_types.go]: Pre-existing validation that ensures that these are unique?

Comment (erikgb) [reply apis/v1/grpcroute_types.go]: I cannot find such validation. Is this a strict requirement? Probably yes, as the api-server will reject a request with duplicate values (if changing this to `set`)?

Comment (JoelSpeed) [reply apis/v1/grpcroute_types.go]: I believe this could be breaking otherwise yes. Unless we can prove that the CRD ratcheting validation would cover this change?

Comment (erikgb) [reply apis/v1/grpcroute_types.go]: Even if the change is technically breaking, I think the key questions are:
1. Does it make sense with duplicate values in this list?
2. Does the order of the values in the list matter?
3. Must the list be owned by a single SSA field manager?

If the answer to all the questions is NO, then I think it could be justified to "break" this as a bug fix.

Comment (robscott) [reply apis/v1/grpcroute_types.go]: I agree that this could/should be considered a bug fix. To keep things clean, I'd recommend starting with `+listType=atomic` in this PR to match the current and unfortunately flawed spec today, and then file a follow up PR to fix this after this initial PR has merged. That will make it easier to point our release notes to a single small PR for the breaking changes that swap `atomic` to `set`.

Comment (erikgb) [reply apis/v1/grpcroute_types.go]: Sounds like a good approach. I will update this PR.

Comment (erikgb) [reply apis/v1/grpcroute_types.go]: @robscott I have now updated the PR, setting all list types to `atomic` for now, and prepared another branch with my proposed "breaking" changes. PTAL!

Comment (erikgb) [reply apis/v1/grpcroute_types.go]: And here is the WIP PR that I will rebase after this PR is merged: https://github.com/kubernetes-sigs/gateway-api/pull/3972

File: hack/openapi-reports/api-violations.list
Comment (youngnick) [inline hack/openapi-reports/api-violations.list:1]: It seems like we really need to keep an eye out for changes to this file after this PR? Should we be considering adding some automation/CI to this to make sure that further changes that add extra rule violations make a PR fail CI?

**Review by youngnick — COMMENTED** [review]
Changes LGTM, just one question about the exceptions file.

File: hack/openapi-reports/api-violations.list
Comment (erikgb) [reply hack/openapi-reports/api-violations.list:1]: Ideally, this file should not change, yes. But some lines from upstream K8s might be removed, but I doubt it, as fixing it would be a breaking change.

When I opened up this PR, I didn't know that KAL was enabled on this project. We can consider reverting this particular change and rely on KAL to report violations instead? If we decide to keep the change as is, I would appreciate merging this PR and create a follow-up issue to track this in CI. WDYT?

Comment (JoelSpeed) [reply hack/openapi-reports/api-violations.list:1]: This exceptions file just tracks missing SSA tags right? And only in upstream types? Given KAL is going to enforce downstream, in theory this list should never be added to/if it were added to, it's out of our control, right?

If it's out of our control, is it worth actually tracking this?

Comment (erikgb) [reply hack/openapi-reports/api-violations.list:1]: > If it's out of our control, is it worth actually tracking this?

I agree, and will revert the changes I made around the openapi reports file.

Comment (erikgb) [reply hack/openapi-reports/api-violations.list:1]: Reverted. PTAL!

**Comment by robscott** [comment]
Thanks @erikgb!

/lgtm

File: apis/v1/grpcroute_types.go (hunk 1 above)
Comment (erikgb) [reply apis/v1/grpcroute_types.go]: @robscott I have now rebased https://github.com/kubernetes-sigs/gateway-api/pull/3972. PTAL!
