### PR TITLE
fix: add CORS to `HTTPRouteFilterType`

### LINKED ISSUE #3649: HTTPRouteFilterType missing CORS, making it impossible to use
Currently we have: `RequestHeaderModifier;ResponseHeaderModifier;RequestMirror;RequestRedirect;URLRewrite;ExtensionRef`

We will need to add one for CORs so it can be used

### PR DESCRIPTION
**Pull request by EyalPazz**
**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:

Fixes #3649 

**Does this PR introduce a user-facing change?**:

```release-note
 Just makes the behavior as expected
```

### CODE REVIEW

File: apis/v1/httproute_types.go [hunk 1]
```diff
@@ -829,7 +829,7 @@ type HTTPRouteFilter struct {
 	// Reason of `UnsupportedValue`.
 	//
 	// +unionDiscriminator
-	// +kubebuilder:validation:Enum=RequestHeaderModifier;ResponseHeaderModifier;RequestMirror;RequestRedirect;URLRewrite;ExtensionRef
+	// +kubebuilder:validation:Enum=RequestHeaderModifier;ResponseHeaderModifier;RequestMirror;RequestRedirect;URLRewrite;ExtensionRef;CORS
```
Comment (robscott) [inline apis/v1/httproute_types.go:832]: Thanks @EyalPazz! This is pretty close, but you need to use an experimental tag so the new option is only available in experimental channel. It should look something like this:
https://github.com/kubernetes-sigs/gateway-api/blob/f0222f41960fac2a967509057e1b93fb4c1a5b56/apis/v1/grpcroute_types.go#L522-L523

Comment (EyalPazz) [reply apis/v1/httproute_types.go]: Got it, my bad :)

**Comment by robscott** [comment]
Thanks @EyalPazz!

/lgtm
/approve
/ok-to-test
