### PR TITLE
fix: Validate requestRedirect with backendrefs

### LINKED ISSUE #2148: Validation Should Prevent Redirect Filters and BackendRefs in same HTTPRoute Rules
**What happened**:
HTTPRoute validation allows the following YAML through:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-filter-rewrite
spec:
  hostnames:
    - rewrite.example
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
      backendRefs:
        - name: example-svc
          port: 80
```

**What you expected to happen**:
Webhook validation to prevent that invalid configuration because BackendRefs are not valid in the same HTTPRoute rule as a RequestRedirect filter.

**Anything else we need to know?**:
This validation should be added roughly in this vicinity: https://github.com/kubernetes-sigs/gateway-api/blob/a5ede12430c31639349ae6c00666890591f72a40/apis/v1beta1/validation/httproute.go#L54

Once the validation is in place, add the example above to https://github.com/kubernetes-sigs/gateway-api/tree/a5ede12430c31639349ae6c00666890591f72a40/hack/invalid-examples/v1beta1/httproute.

### PR DESCRIPTION
**Pull request by slayer321**
**What type of PR is this?**

/kind bug
/kind test
**What this PR does / why we need it**:
Validate and  Prevent Redirect Filters and BackendRefs in same HTTPRoute Rules.
**Which issue(s) this PR fixes**:

Fixes #2148

**Does this PR introduce a user-facing change?**:

```release-note
Webhook validation now ensures that BackendRefs can not be specified in the same HTTPRoute rule as a Redirect filter
```

### CODE REVIEW

**Comment by gyohuangxin** [comment]
@slayer321 The job failed due to a lint error:
```
./hack/invalid-examples/v1beta1/httproute/invalid-request-redirect-with-backendref.yaml
  16:19     error    no new line character at the end of file  (new-line-at-end-of-file)
[0;31mTest FAILED: hack/../hack/verify-yamllint.sh 
make: *** [Makefile:114: verify] Error 1
```

**Review by gyohuangxin — APPROVED** [review]
LGTM, thanks!

File: apis/v1alpha2/validation/httproute_test.go [hunk 1]
```diff
@@ -868,7 +868,7 @@ func TestValidateHTTPRouteTypeMatchesField(t *testing.T) {
 				StatusCode: new(int),
 			},
 		},
-		errCount: 0,
+		errCount: 1,
```
Comment (arkodg) [inline apis/v1alpha2/validation/httproute_test.go:871]: why has this changed ?

File: apis/v1beta1/validation/httproute_test.go [hunk 2]
```diff
@@ -1049,7 +1075,7 @@ func TestValidateHTTPRouteTypeMatchesField(t *testing.T) {
 				StatusCode: new(int),
 			},
 		},
-		errCount: 0,
+		errCount: 1,
```
Comment (arkodg) [inline apis/v1beta1/validation/httproute_test.go:1078]: why has this changed ?

File: apis/v1beta1/validation/httproute.go [hunk 3]
```diff
@@ -77,6 +78,17 @@ func ValidateHTTPRouteSpec(spec *gatewayv1b1.HTTPRouteSpec, path *field.Path) fi
 	return errs
 }
 
+// validateRequestRedirectFiltersWithBackendRefs validates that RequestRedirect filters are not used with backendRefs
+func validateRequestRedirectFiltersWithBackendRefs(rule gatewayv1b1.HTTPRouteRule, path *field.Path) field.ErrorList {
+	var errs field.ErrorList
+	for _, filter := range rule.Filters {
+		if filter.RequestRedirect != nil && len(rule.BackendRefs) > 0 {
+			errs = append(errs, field.Invalid(path.Child("filters"), filter, "RequestRedirect filter is not allowed with backendRefs"))
```
Comment (arkodg) [inline apis/v1beta1/validation/httproute.go:86]: is `filter,` needed ?

File: apis/v1alpha2/validation/httproute_test.go (hunk 1 above)
Comment (slayer321) [reply apis/v1alpha2/validation/httproute_test.go:871]: The same reason that I mentioned for `v1beta1` changes.

File: apis/v1beta1/validation/httproute_test.go (hunk 2 above)
Comment (slayer321) [reply apis/v1beta1/validation/httproute_test.go:1078]: So, as in this issue we need to validate that BackendRefs is not used when Redirect Filters  are used in httpRoute. 
In this [example](https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1beta1/validation/httproute_test.go#L1041) as we can see that we are using Redirect Filters and then in the for loops we have [BackendRefs](https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1beta1/validation/httproute_test.go#L1125) as well. 

After I added a check of it inside `validation/httproute.go`. The test started failing so I made the `errCount` as 1 .

File: apis/v1beta1/validation/httproute.go (hunk 3 above)
Comment (slayer321) [reply apis/v1beta1/validation/httproute.go:86]: If you are asking if `filter` needed inside the `field.Invalid` function. So yeah I think we can change to `gatewayv1b1.HTTPRouteFilterRequestRedirect` .. as it will be more specific.
```
errs = append(errs, field.Invalid(path.Child("filters"), gatewayv1b1.HTTPRouteFilterRequestRedirect, "RequestRedirect filter is not allowed with backendRefs"))
```

Comment (arkodg) [reply apis/v1beta1/validation/httproute.go:86]: thanks, yeah +1 to this change

File: apis/v1beta1/validation/httproute_test.go (hunk 2 above)
Comment (arkodg) [reply apis/v1beta1/validation/httproute_test.go:1078]: ah thanks for the clarification, didnt go through at the entire file earlier 🙈 
would be good to add a positive test case, maybe as a new standalone function that ensures thats when the Redirect filter exists and no backendRefs are set, validation is successful

Comment (arkodg) [reply apis/v1beta1/validation/httproute_test.go:1078]: was referring to a standalone alone test `TestValidateRequestRedirectFiltersWithNoBackendRef`
anyways this is a good to have and is non blocking

**Review by arkodg — APPROVED** [review]
LGTM thanks !

**Comment by slayer321** [comment]
Hi, as api-verify CI is failing so I tried running the `golangci-lint run` command .. but it is just showing Killed 
```
sachinmaurya@sachin:~/go/src/github.com/gateway-api (test-request-route-w-backend-ref)$ golangci-lint run 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
Killed
```
What can be the reason for that :thinking:

**Comment by arkodg** [comment]
> golangci-lint run

@slayer321  can you rebase to `main` and try `./hack/verify-golint.sh` ?

**Comment by slayer321** [comment]
I tried it but still got below error 
```
sachinmaurya@sachin:~/go/src/github.com/gateway-api (test-request-route-w-backend-ref)$ ./hack/verify-golint.sh
level=warning msg="[runner] Can't run linter goanalysis_metalinter: musttag: running `go list all`: exit status 1"
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: musttag: running `go list all`: exit status 1\n\n"
```
After looking for it , I found that there where many similar errors but nothing same as this one. most of them says that we need to run `go build`.
has anyone else faced the similar error while working on this project or is it some issue with my local setup.

**Comment by gyohuangxin** [comment]
@slayer321 I don't have idea about it. Even if you can't run the `./hack/verify-golint.sh` in your environment, you can find the details from the CI job logs: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_gateway-api/2161/pull-gateway-api-verify/1676963399549849600

File: apis/v1alpha2/validation/httproute_test.go (hunk 1 above)
Comment (robscott) [reply apis/v1alpha2/validation/httproute_test.go:871]: @slayer321 do you happen to have a link handy to that comment or can you just copy it here? Not finding the context easily and also have the same question.

Comment (slayer321) [reply apis/v1alpha2/validation/httproute_test.go:871]: I was taking about this comment https://github.com/kubernetes-sigs/gateway-api/pull/2161#discussion_r1251477315

**Comment by robscott** [comment]
/release-note "Webhook validation now ensures that BackendRefs can not be specified in the same HTTPRoute rule as a Redirect filter"

**Comment by robscott** [comment]
/release-note-edit ```Webhook validation now ensures that BackendRefs can not be specified in the same HTTPRoute rule as a Redirect filter```

**Comment by robscott** [comment]
Thanks @slayer321!

/lgtm
/approve
