### PR TITLE
Removes ForwardTo References Throughout

### LINKED ISSUE #1831: API Overview Doc Still References ForwardTo
**What happened**:
The API overview doc contains a [request flow](https://gateway-api.sigs.k8s.io/concepts/api-overview/#request-flow) section that uses `forwardTo` instead of `backendRefs`.

**What you expected to happen**:
Use the proper terminology- `backendedRefs`.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
No

### PR DESCRIPTION
**Pull request by danehans**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Removes stale `forwardTo` references or updates the reference to `backendRefs`.

**Which issue(s) this PR fixes**:

Fixes #1831 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/admission/server_test.go [hunk 1]
```diff
@@ -285,9 +285,9 @@ func TestServeHTTPSubmissions(t *testing.T) {
    								               }
    								            }
    								         ],
-   								         "forwardTo": [
```
Comment (youngnick) [inline pkg/admission/server_test.go:288]: tbh kinda worrying that this was passing the tests. I wonder if we're not running this one?

**Review by youngnick — COMMENTED** [review]
Thanks @danehans!

/lgtm
/approve
