### PR TITLE
fix: add BackendTLSPolicy features to GATEWAY-HTTP profile

### LINKED ISSUE #3936: BackendTLSPolicy Conformance Test - consider including the feature in the GATEWAY-HTTP profile or create a dedicated profile
See https://github.com/kubernetes-sigs/gateway-api/pull/3212#discussion_r2206863791

### PR DESCRIPTION
**Pull request by snorwin**
**What type of PR is this?**

/kind bug
/area conformance-test

**What this PR does / why we need it**:
This PR ensures that the `BackendTLSPolicy` conformance tests are properly included in the conformance profiles and reflected in the generated reports. Currently, these tests run successfully but don’t appear in the report because they aren’t associated with any profile

**Which issue(s) this PR fixes**:

Fixes #3936

**Does this PR introduce a user-facing change?**:

```release-note
Added BackendTLSPolicy features to GATEWAY-HTTP profile
```

### CODE REVIEW

File: pkg/features/backendtlspolicy.go [hunk 1]
```diff
@@ -43,14 +43,9 @@ var BackendTLSPolicySanValidationFeature = Feature{
 	Channel: FeatureChannelStandard,
 }
 
-// BackendTLSPolicyCoreFeatures includes all the supported features for the
-// BackendTLSPolicy API at a Core level of support.
-var BackendTLSPolicyCoreFeatures = sets.New(
-	BackendTLSPolicyFeature,
-)
-
```
Comment (snorwin) [inline pkg/features/backendtlspolicy.go]: I wasn’t sure if BackendTLSPolicy is considered Core or Extended.

File: conformance/utils/suite/profiles.go [hunk 2]
```diff
@@ -81,6 +81,8 @@ var (
 			Insert(features.SetsToNamesSet(
 				features.GatewayExtendedFeatures,
 				features.HTTPRouteExtendedFeatures,
+				features.BackendTLSPolicyCoreFeatures,
+				features.BackendTLSPolicyExtendedFeatures,
```
Comment (snorwin) [inline conformance/utils/suite/profiles.go:85]: I added now the BackendTLSPolicy Core feature to the Extended features of the profile, I wasn’t sure if the overall BackendTLSPolicy is considered Core or Extended.

Comment (candita) [reply conformance/utils/suite/profiles.go:85]: I wonder if we should create a new profile for Policies.

Comment (snorwin) [reply conformance/utils/suite/profiles.go:85]: In my opinion, I don’t think it’s worth creating a new profile at this point. Currently, there are only two features that would be part of such a dedicated profile, and both require the Gateway and HTTPRoute feature to execute the tests anyway. Therefore, it would make much more sense to include them under GATEWAY-HTTP for now, and potentially later also under GATEWAY-GRPC and GATEWAY-TLS, once we’ve written the corresponding conformance tests.

The main question for me is whether BackendTLSPolicy is considered part of the Core or Extended. I couldn’t find any information about this in the GEP. If we add it to Core, all implementations would need to support it before achieving conformance for version 1.4, which, in my opinion, would be quite challenging for some. Therefore, I’d suggest adding it as part of the Extended features for now.

Comment (youngnick) [reply conformance/utils/suite/profiles.go:85]: The guideline is that all additional objects should be considered Extended unless there is a good reason.

This comes back to "what does Extended mean?". The word "Extended" is relevant for a field _and all of its child features_. So, when a whole object is Extended, that means that you don't have to support that object. However, if you do support it, then _within_ that object, Core features are MUST, and Extended features are SHOULD.

So, the BackendTLSPolicyExtendedFeatures really require BackendTLSPolicyCoreFeatures _and_ BackendTLSPolicyExtendedFeatures.

So, yes, I agree that BackendTLSPolicy should be Extended. At some point, it may be worth moving it into overall Core support for the HTTP Profile, but not yet.

Comment (snorwin) [reply conformance/utils/suite/profiles.go:85]: @youngnick Just to make sure I understand correctly, are you suggesting that we add BackendTLSPolicyCoreFeatures to BackendTLSPolicyExtendedFeatures, or should we keep the change as it is?

Comment (candita) [reply conformance/utils/suite/profiles.go:85]: I'd like to see features.BackendTLSPolicyCoreFeatures added to a new conformanceProfile for policies.

```suggestion
       PolicyConformanceProfile = ConformanceProfile{
		Name: GatewayHTTPConformanceProfileName,
		CoreFeatures: sets.New(
			features.BackendTLSPolicyCoreFeatures,
		),
		ExtendedFeatures: sets.New[features.FeatureName]().
			Insert(features.SetsToNamesSet(
				features.BackendTLSPolicyExtendedFeatures,
...
```

**Comment by snorwin** [comment]
@youngnick here is an example of how the conformance profile for `GATEWAY-HTTP` looks for an implementation that supports BackendTLSPolicy:
```
profiles:
  - core:
      result: success
      statistics:
        Failed: 0
        Passed: 33
        Skipped: 0
    extended:
      result: success
      statistics:
        Failed: 0
        Passed: 26
        Skipped: 0
      supportedFeatures:
        - BackendTLSPolicy
        - BackendTLSPolicySANValidation
        - GatewayInfrastructurePropagation
        - GatewayPort8080
        - HTTPRouteBackendProtocolH2C
        - HTTPRouteBackendProtocolWebSocket
        - HTTPRouteBackendTimeout
        - HTTPRouteCORS
        - HTTPRouteDestinationPortMatching
        - HTTPRouteHostRewrite
        - HTTPRouteMethodMatching
        - HTTPRouteNamedRouteRule
        - HTTPRouteParentRefPort
        - HTTPRoutePathRedirect
        - HTTPRoutePathRewrite
        - HTTPRoutePortRedirect
        - HTTPRouteQueryParamMatching
        - HTTPRouteRequestTimeout
        - HTTPRouteResponseHeaderModification
        - HTTPRouteSchemeRedirect
      unsupportedFeatures:
        - GatewayAddressEmpty
        - GatewayHTTPListenerIsolation
        - GatewayStaticAddresses
        - HTTPRoute303RedirectStatusCode
        - HTTPRoute307RedirectStatusCode
        - HTTPRoute308RedirectStatusCode
        - HTTPRouteBackendRequestHeaderModification
        - HTTPRouteRequestMirror
        - HTTPRouteRequestMultipleMirrors
        - HTTPRouteRequestPercentageMirror
    name: GATEWAY-HTTP
    summary: Core tests succeeded. Extended tests succeeded.
    succeededProvisionalTests:
      - GatewayInfrastructure
      - HTTPRouteNamedRule
```
(If an implementation does not support BackendTLSPolicy, the related features will be listed under `unsupportedFeatures`)

**Comment by youngnick** [comment]
Okay, thanks for checking @snorwin.

This LGTM then.

/approve

**Comment by snorwin** [comment]
I think this is ready to merge and to be cherry-picked into `release-1.4`.

/assign @robscott

File: conformance/utils/suite/profiles.go (hunk 2 above)
Comment (candita) [reply conformance/utils/suite/profiles.go:85]: Disregard.
