### PR TITLE
generator: omit top-level CRD status from manifests

### LINKED ISSUE #4402: Standard CRD manifests contain invalid `null` values in `.status` fields, breaking schema validation
**What happened**:

The install YAML manifests for v1.4.1 (and potentially earlier versions) contain explicit `null` values for `.status.conditions` and `.status.storedVersions` in the CustomResourceDefinition objects.

Example from `gateway.networking.k8s.io_gateways.yaml`:

https://github.com/kubernetes-sigs/gateway-api/blob/477d172e6ac5eccb82b65781ddb8f924afec4170/config/crd/standard/gateway.networking.k8s.io_gateways.yaml#L2248-L2253

According to the [Kubernetes API Reference (CRD v1)](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.35/#customresourcedefinitionstatus-v1-apiextensions-k8s-io), these fields cannot be `null`:

- `.status.conditions`: Must be an array (or omitted).
- `.status.storedVersions`: Must be an string array (or omitted).

This causes CI/CD pipelines using strict validation tools like [kubeconform](https://github.com/yannh/kubeconform) to fail.

**What you expected to happen**:

Static manifest files intended for installation should ideally not contain a `.status` block at all.
If the block is present, the fields within it must adhere to the OpenAPI schema (i.e., be empty arrays rather than `null`).

**How to reproduce it (as minimally and precisely as possible)**:

You can validate the release artifact against the official Kubernetes JSON schema using `kubeconform`:

```bash
$ curl -sL https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml | kubeconform -schema-location "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{.NormalizedKubernetesVersion}}/{{.ResourceKind}}.json"
stdin - CustomResourceDefinition gatewayclasses.gateway.networking.k8s.io is invalid: problem validating schema. Check JSON formatting: jsonschema validation failed with 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/customresourcedefinition.json#' - at '/status': validation failed   - at '/status/conditions': got null, want array   - at '/status/storedVersions': got null, want array
stdin - CustomResourceDefinition backendtlspolicies.gateway.networking.k8s.io is invalid: problem validating schema. Check JSON formatting: jsonschema validation failed with 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/customresourcedefinition.json#' - at '/status': validation failed   - at '/status/conditions': got null, want array   - at '/status/storedVersions': got null, want array
stdin - CustomResourceDefinition referencegrants.gateway.networking.k8s.io is invalid: problem validating schema. Check JSON formatting: jsonschema validation failed with 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/customresourcedefinition.json#' - at '/status': validation failed   - at '/status/conditions': got null, want array   - at '/status/storedVersions': got null, want array
stdin - CustomResourceDefinition grpcroutes.gateway.networking.k8s.io is invalid: problem validating schema. Check JSON formatting: jsonschema validation failed with 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/customresourcedefinition.json#' - at '/status': validation failed   - at '/status/storedVersions': got null, want array   - at '/status/conditions': got null, want array
stdin - CustomResourceDefinition gateways.gateway.networking.k8s.io is invalid: problem validating schema. Check JSON formatting: jsonschema validation failed with 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/customresourcedefinition.json#' - at '/status': validation failed   - at '/status/conditions': got null, want array   - at '/status/storedVersions': got null, want array
stdin - CustomResourceDefinition httproutes.gateway.networking.k8s.io is invalid: problem validating schema. Check JSON formatting: jsonschema validation failed with 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/customresourcedefinition.json#' - at '/status': validation failed   - at '/status/conditions': got null, want array   - at '/status/storedVersions': got null, want array
```

**Anything else we need to know?**:

Thanks 💚

### PR DESCRIPTION
**Pull request by MatteoFari**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
This PR fixes how CRD files are generated.

Right now, the generated install YAML includes a top-level `status` field in `CustomResourceDefinition` objects. That field contains invalid `null` values, which causes tools like `kubeconform` to fail. Since `status` is filled in by Kubernetes, it should not be in static install files.

This change removes that field from generated manifests and regenerates the CRDs.

**Which issue(s) this PR fixes**:

Fixes #4402

**Does this PR introduce a user-facing change?**:

```release-note
Generated Gateway API CRD install manifests no longer include top-level CustomResourceDefinition status fields with invalid null values, fixing strict schema validation failures in tools such as kubeconform.
```

### CODE REVIEW

**Comment by youngnick** [comment]
Sure, this seems fine to me.

/approve

File: tools/generator/main.go [hunk 1]
```diff
@@ -160,6 +172,15 @@ func main() {
 	}
 }
 
+func marshalCRDManifest(crd apiext.CustomResourceDefinition) ([]byte, error) {
```
Comment (rikatz) [inline tools/generator/main.go]: please use a different argument name here to not shadow with  the import of "sigs.k8s.io/controller-tools/pkg/crd"

**Comment by rikatz** [comment]
/ok-to-test
One minor comment, otherwise lgtm
