### PR TITLE
apis: validate header and query param matches

### LINKED ISSUE #1225: clarify behavior of multiple query param matches for the same key
The spec does not indicate what should be done if a route ~rule~ match has multiple query param matches for the same key.

For header matches, guidance is given to use the first match for a given header name, and to ignore subsequent ones for the same name (see https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPHeaderMatch).

I'd suggest adding the same guidance for query params, with the exception that query param names be case-sensitive. If this makes sense, I'll open a PR to add this to the spec. (I should also be able to add a conformance test for query params that includes this soon).

### PR DESCRIPTION
**Pull request by skriss**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Adds webhook validation to ensure that no
HTTP header or query param is matched more
than once in a given route rule. Also updates
the godoc for HTTPQueryParamMatch to be
consistent with HTTPHeaderMatch.

**Which issue(s) this PR fixes**:

Fixes #1225 

**Does this PR introduce a user-facing change?**:

```release-note
Adds webhook validation to ensure that no HTTP header or query param is matched more than once in a given route rule.
```

### CODE REVIEW

File: apis/v1alpha2/validation/httproute_test.go [hunk 1]
```diff
@@ -572,6 +572,128 @@ func TestValidateHTTPPathMatch(t *testing.T) {
...
+				}},
+			}}
+
+			errs := ValidateHTTPRoute(&route)
+			if len(errs) != tc.errCount {
+				t.Errorf("got %d errors, want %d errors: %s", len(errs), tc.errCount, errs)
+			}
+		})
+	}
+}
```
Comment (shaneutt) [inline apis/v1alpha2/validation/httproute_test.go:634]: Perhaps a bit of a nitpick: How do you feel about verifying the error contents as well?

File: apis/v1alpha2/validation/httproute_test.go [hunk 2]
```diff
@@ -572,6 +572,128 @@ func TestValidateHTTPPathMatch(t *testing.T) {
...
```
Comment (shaneutt) [inline apis/v1alpha2/validation/httproute_test.go:695]: Similar to the above, any thoughts on verifying the error contents?

**Review by shaneutt — COMMENTED** [review]
No blockers, thanks for taking the time and thanks for adding the validation!

Just a couple smaller comments but I think this is just about ready to go.

File: apis/v1alpha2/validation/httproute_test.go (hunk 1 above)
Comment (skriss) [reply apis/v1alpha2/validation/httproute_test.go:634]: Yeah I can do that; the rest of the tests in this file are only verifying error counts so I went with that for consistency but agree it'd be a bit better to verify specific errors.

**Review by shaneutt — APPROVED** [review]
/lgtm
