### PR TITLE
fix: allow the header based session persistence not to have AbsoluteTimeout

### LINKED ISSUE #3214: Header based session persistence cannot be configured without `AbsoluteTimeout`
**What happened**:

Header based session persistence cannot be configured without `AbsoluteTimeout`.

If you apply -

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: envoy-header-based-session-persistence
  namespace: gateway-conformance-infra
spec:
  parentRefs:
    - name: same-namespace
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: infra-backend-v1
          port: 8080
        - name: infra-backend-v2
          port: 8080
      sessionPersistence:
        sessionName: session-a
        type: Header
```

it hits the validation issue:

```shell
AbsoluteTimeout must be specified when cookie lifetimeType is Permanent
```

**What you expected to happen**:

Header based session persistence shouldn't have `CookieConfig`, and it should be allowed Header based session persistence not to have `AbsoluteTimeout`.

**How to reproduce it (as minimally and precisely as possible)**:

Just apply -

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: envoy-header-based-session-persistence
  namespace: gateway-conformance-infra
spec:
  parentRefs:
    - name: same-namespace
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: infra-backend-v1
          port: 8080
        - name: infra-backend-v2
          port: 8080
      sessionPersistence:
        sessionName: session-a
        type: Header
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by sanposhiho**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR scope out the header based session persistence from the validation `AbsoluteTimeout must be specified when cookie lifetimeType is Permanent`.

See https://github.com/kubernetes-sigs/gateway-api/issues/3214.

**Which issue(s) this PR fixes**:

Fixes #3214

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: apis/v1/shared_types.go [hunk 1]
```diff
@@ -745,7 +745,7 @@ const (
 )
 
 // SessionPersistence defines the desired state of SessionPersistence.
-// +kubebuilder:validation:XValidation:message="AbsoluteTimeout must be specified when cookie lifetimeType is Permanent",rule="!has(self.cookieConfig.lifetimeType) || self.cookieConfig.lifetimeType != 'Permanent' || has(self.absoluteTimeout)"
+// +kubebuilder:validation:XValidation:message="AbsoluteTimeout must be specified when cookie lifetimeType is Permanent",rule="self.type == 'Header' || !has(self.cookieConfig.lifetimeType) || self.cookieConfig.lifetimeType != 'Permanent' || has(self.absoluteTimeout)"
```
Comment (gauravkghildiyal) [inline apis/v1/shared_types.go:748]: The issue with the CEL config is that it assumes `self.cookieConfig` will always be set (which is not the case which is why it fail).

I believe we should not be special casing this for the `Header` type, but rather fix the underlying cause and use

```
!has(self.cookieConfig)
```

The eventual expression becomes:

```
!has(self.cookieConfig) || self.cookieConfig.lifetimeType != 'Permanent' || has(self.absoluteTimeout)
```

**Comment by robscott** [comment]
Thanks @sanposhiho! Will defer to @gcs278 on this one, but this looks correct to me.

**Comment by gauravkghildiyal** [comment]
Thanks! 
/lgtm

**Comment by gcs278** [comment]
Good catch, I missed this with the initial revision, and thanks for the fix!
/lgtm

**Comment by sanposhiho** [comment]
Thanks for the review, everyone. What's the rule around `/hold` label in the project? Is it OK to just `/unhold`?

**Comment by robscott** [comment]
Thanks @sanposhiho!

We automatically add holds on any PR that modifies a GEP because we require at least two approvals on those. We've met that criteria here, so let's get this merged.

/hold cancel
