### PR TITLE
Return the behaviour of a new default GRPC client instantiation for every request

### LINKED ISSUE #3122: GRPCRoute conformance tests failing with `client connection is closing`
**What happened**:

Our GRPCRoute conformance tests are failing running against the main branch with 

`RPC finished with error: rpc error: code = Canceled desc = grpc: the client connection is closing`

These are running and working successfully against v1.1.0.

**What you expected to happen**:

The requests are not cancelled and the tests pass

**How to reproduce it (as minimally and precisely as possible)**:

Run the conformance test suite against any implementation using the default GRPC client

**Anything else we need to know?**:

As far as I can tell, this is happening as a result of https://github.com/kubernetes-sigs/gateway-api/pull/3095.

As part of the changes introduced in this PR, we are sharing one client between all requests instead of instantiating a new client for every GRPC request. However, each request is still calling `defer c.Close()` which means the client connection will be closed when this function returns even if another request is using the connection. Additionally, each call to `sendRPC` sets the connection specific to the call being made, and will reset the current connection if present. Because the tests run in parallel, this is causing conflicts and race conditions. 

Example conformance test run with the failures: https://github.com/nginxinc/nginx-gateway-fabric/actions/runs/9312728851/job/25634135132

### PR DESCRIPTION
**Pull request by ciarams87**
**What type of PR is this?**

/kind bug
/area conformance

**What this PR does / why we need it**:

Returns the GRPCRoute conformance tests default client to instantiating a new client for every request, instead of creating one shared client for all requests, as this is leading to conflicts and closed client connections. More details in the issue: https://github.com/kubernetes-sigs/gateway-api/issues/3122

**Which issue(s) this PR fixes**:

Fixes #3122 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by snehachhabria** [comment]
thanks for the fix @ciarams87, the changes lgtm!

**Review by gnossen — APPROVED** [review]

File: conformance/utils/grpc/grpc.go [hunk 1]
```diff
@@ -270,6 +270,9 @@ func validateExpectedResponse(t *testing.T, expected ExpectedResponse) {
 func MakeRequestAndExpectEventuallyConsistentResponse(t *testing.T, c Client, timeoutConfig config.TimeoutConfig, gwAddr string, expected ExpectedResponse) {
 	t.Helper()
 	validateExpectedResponse(t, expected)
+	if c == nil {
+		c = &DefaultClient{Conn: nil}
+	}
 	defer c.Close()
```
Comment (gauravkghildiyal) [inline conformance/utils/grpc/grpc.go:276]: While the change does help address the immediate concern, it does seem to reveal a flaw here -- I would expect the client to only be closed by `MakeRequestAndExpectEventuallyConsistentResponse()` when it was instantiated within `MakeRequestAndExpectEventuallyConsistentResponse()` itself. 

When a non-nil client is passed to the `MakeRequestAndExpectEventuallyConsistentResponse()`, this function should not own the lifecycle the passed-clients lifecycle.

An implication of this would be that the Client interface should not have the `Close` function.

**Review by gauravkghildiyal — COMMENTED** [review]
Thanks for catching this, @ciarams87!

I have shared some thoughts, though perhaps we may want to address those independently of this PR (and not necessarily by you)

/ok-to-test

File: conformance/utils/grpc/grpc.go (hunk 1 above)
Comment (ciarams87) [reply conformance/utils/grpc/grpc.go:276]: Thanks for the review!


> When a non-nil client is passed to the MakeRequestAndExpectEventuallyConsistentResponse(), this function should not own the lifecycle the passed-clients lifecycle.
An implication of this would be that the Client interface should not have the Close function.

That makes a lot of sense to me, but I'm not entirely sure that should be addressed in this PR - the scope here is only to return the DefaultClient behaviour to how it was before. I'd like to defer to @snehachhabria as the original author of https://github.com/kubernetes-sigs/gateway-api/pull/3095 as to the decisions made in this respect.

Comment (snehachhabria) [reply conformance/utils/grpc/grpc.go:276]: @gauravkghildiyal what you suggested should be done and can be handled in a separate PR. Once this PR is merged, I can handle the suggested changes.

Comment (gauravkghildiyal) [reply conformance/utils/grpc/grpc.go:276]: Thanks @ciarams87 and @snehachhabria!

**Review by gauravkghildiyal — COMMENTED** [review]
This LGTM (has [follow-up items](https://github.com/kubernetes-sigs/gateway-api/pull/3130/files#r1635872850) which will be tackled separately). 
I see @arkodg on the reviewers list who can help with conformance approval.

/lgtm

**Review by arkodg — APPROVED** [review]
/approve
/lgtm

thanks !
