### PR TITLE
Ensure listener name must be unique within a Gateway

### LINKED ISSUE #1845: Listener name must be unique within a Gateway
**What happened**:

According to https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.Listener

> Name is the name of the Listener. This name MUST be unique within a Gateway.

However, it seems gateway-api doesn't check the name currently.

**What you expected to happen**:

The listener with the duplicate name should be rejected.

**How to reproduce it (as minimally and precisely as possible)**:

A configuration like this can be incorrectly accepted:
```
  kind: Gateway
  metadata:
    namespace: envoy-gateway
    name: gateway-1
  spec:
    gatewayClassName: envoy-gateway-class
    listeners:
    - name: http-1
      protocol: HTTP
      port: 8080
    - name: http-1
      protocol: HTTP
      port: 80

```

**Anything else we need to know?**:

The issue is originally raised at https://github.com/envoyproxy/gateway/issues/1180 and I have provided an initial fix in https://github.com/envoyproxy/gateway/pull/1181. I could rewrite the fix to adapt gateway-api's code if the report is accepted.

### PR DESCRIPTION
**Pull request by muyuan0**
Signed-off-by: muyuan0 <127020730+muyuan0@users.noreply.github.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Check if the listener names are unique within a Gateway

**Which issue(s) this PR fixes**:

Fixes #1845

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: apis/v1beta1/validation/gateway.go [hunk 1]
```diff
@@ -118,3 +119,17 @@ func ValidateTLSCertificateRefs(listeners []gatewayv1b1.Listener, path *field.Pa
 	}
 	return errs
 }
+
+// ValidateListenerNames validates the names of the listeners
+// must be unique within the Gateway
+func ValidateListenerNames(listeners []gatewayv1b1.Listener, path *field.Path) field.ErrorList {
```
Comment (danehans) [inline apis/v1beta1/validation/gateway.go:125]: This func should be called by `validateGatewayListeners()` to be included in the admission webhook.

**Comment by shaneutt** [comment]
> I think we should sort out some of the discussions in the following related issues prior to merging this change
> 
> #1842 #1713

So just to be clear you're asking that this PR be put on _hold_ until both #1842 and #1713 are resolved?

**Comment by dprotaso** [comment]
Yeah.

File: apis/v1beta1/validation/gateway.go (hunk 1 above)
Comment (muyuan0) [reply apis/v1beta1/validation/gateway.go:125]: Added in the `validateGatewayListeners` above

**Comment by shaneutt** [comment]
> Yeah.

I'm not feeling very compelled to block here, it seems unique listener name checking is something we would want in any case, no?

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by robscott** [comment]
@dprotaso I'm not sure I see the connection between this and the issues you linked, can you help clarify why they should block this?

**Comment by dprotaso** [comment]
Yeah #1842 doesn't apply to `Name` (`SectionName`) - my mistake

For https://github.com/kubernetes-sigs/gateway-api/issues/1713 I wondered if we're merging Gateways would we allow listeners on different Gateways to merge with the same `Name`.  A concern I had was that the validation here would prevent that but I might have been overzealous. We can have that discussion in the other GEP

**Review by shaneutt — APPROVED** [review]
/lgtm

**Comment by shaneutt** [comment]
@muyuan0 just need to change your commit message as per https://github.com/kubernetes-sigs/gateway-api/pull/1854#issuecomment-1475899793 and then we're all set :+1:

**Comment by muyuan0** [comment]
@shaneutt 
Could I force push to update the commit message?

**Comment by shaneutt** [comment]
> @shaneutt Could I force push to update the commit message?

Yes that's fine! Thank you!

**Comment by robscott** [comment]
Thanks @muyuan0! This LGTM as well once the commit message is fixed.

**Comment by robscott** [comment]
Thanks @muyuan0!

/lgtm
